// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applications": {
            "post": {
                "description": "Загружает PDF, получает описание вакансии из БД, анализирует ИИ и сохраняет результат",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "portal"
                ],
                "summary": "Подать отклик на вакансию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID кандидата",
                        "name": "candidate_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID вакансии",
                        "name": "vacancy_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Резюме PDF",
                        "name": "resume",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/applications/{id}": {
            "get": {
                "description": "Возвращает подробную информацию о конкретном отклике по его ID. (Маршрут: /:id, где id - это ID заявки)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Полная информация о заявке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID заявки (application_id)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Объект заявки",
                        "schema": {
                            "$ref": "#/definitions/models.Application"
                        }
                    },
                    "404": {
                        "description": "Заявка не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/applications/{id}/ai-data": {
            "get": {
                "description": "Получает вердикт, скоринг и распознанный текст резюме",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Результаты анализа ИИ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID заявки (application_id)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные анализа",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Данные не найдены",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/applications/{id}/status": {
            "patch": {
                "description": "Обновляет статус конкретного отклика (например: 'Интервью', 'Оффер', 'Отказ') по его ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Изменение статуса заявки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID заявки (application_id)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка БД",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/candidate/login": {
            "post": {
                "description": "Аутентификация пользователя как кандидата. Проверяет email и пароль в таблице candidates.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход для соискателя",
                "parameters": [
                    {
                        "description": "Учетные данные соискателя",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные: { 'id': '...', 'email': '...', 'role': 'candidate', 'telegram_username': '...' }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка: Неверный формат входных данных",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Ошибка: Неверный email или пароль",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/candidate/signup": {
            "post": {
                "description": "Создает аккаунт кандидата, сохраняя email и никнейм в Telegram для последующей связи.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация соискателя",
                "parameters": [
                    {
                        "description": "Данные для регистрации соискателя",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                },
                                "telegram_username": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пример: { 'token': '...', 'candidate_id': '...' }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка: Некорректные данные",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Ошибка: Почта уже используется",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/recruiter/login": {
            "post": {
                "description": "Аутентификация пользователя как рекрутера. Проверяет email и пароль в таблице recruiters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход для рекрутера",
                "parameters": [
                    {
                        "description": "Учетные данные рекрутера",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные: { 'id': '...', 'email': '...', 'role': 'recruiter', 'company_name': '...' }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка: Неверный формат входных данных",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Ошибка: Неверный email или пароль",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/recruiter/signup": {
            "post": {
                "description": "Создает новый аккаунт рекрутера с безопасным хешированием пароля через bcrypt.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация рекрутера",
                "parameters": [
                    {
                        "description": "Данные для регистрации рекрутера",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "company_name": {
                                    "type": "string"
                                },
                                "email": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пример: { 'token': '...', 'recruiter_id': '...' }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка: Неверный формат входных данных",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Ошибка: Пользователь с таким Email уже существует",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка: Критическая ошибка при хешировании или сохранении",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/my-applications": {
            "get": {
                "description": "Получение истории всех откликов текущего кандидата",
                "tags": [
                    "portal"
                ],
                "summary": "Мои отклики",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID кандидата",
                        "name": "candidate_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/templates": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Список всех шаблонов рекрутера",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID рекрутера",
                        "name": "recruiter_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MessageTemplate"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Создать шаблон сообщения",
                "parameters": [
                    {
                        "description": "Данные шаблона",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "body_text": {
                                    "type": "string"
                                },
                                "recruiter_id": {
                                    "type": "string"
                                },
                                "title": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/templates/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Обновить шаблон",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID шаблона",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новые данные",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "body_text": {
                                    "type": "string"
                                },
                                "title": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "templates"
                ],
                "summary": "Удалить шаблон",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID шаблона",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Deleted",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/templates/{id}/generate": {
            "post": {
                "description": "Генерирует текст сообщения и ссылку на чат по шаблону",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruiter_tools"
                ],
                "summary": "Генерация сообщения для Telegram",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID шаблона",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные кандидата",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "candidate_name": {
                                    "type": "string"
                                },
                                "telegram_username": {
                                    "type": "string"
                                },
                                "vacancy_title": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Текст и ссылка",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка входных данных",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Шаблон не найден",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vacancies": {
            "post": {
                "description": "Создает новую вакансию и автоматически генерирует short_link",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vacancies"
                ],
                "summary": "Создание вакансии",
                "parameters": [
                    {
                        "description": "Объект вакансии",
                        "name": "vacancy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VacancyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Vacancy created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vacancies/active": {
            "get": {
                "description": "Получает все незаархивированные вакансии",
                "tags": [
                    "vacancies"
                ],
                "summary": "Список активных вакансий",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Vacancy"
                            }
                        }
                    }
                }
            }
        },
        "/vacancies/all": {
            "get": {
                "description": "Получает список всех вакансий рекрутера (и активных, и архивных)",
                "tags": [
                    "vacancies"
                ],
                "summary": "Список всех вакансий",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID рекрутера у которого вытаскиваются все вакансии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Vacancy"
                            }
                        }
                    }
                }
            }
        },
        "/vacancies/inactive": {
            "get": {
                "description": "Получает список только неактивных (заархивированных) вакансий",
                "tags": [
                    "vacancies"
                ],
                "summary": "Список архивных вакансий",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Vacancy"
                            }
                        }
                    }
                }
            }
        },
        "/vacancies/link/{short_link}": {
            "get": {
                "description": "Получение деталей вакансии через short_link",
                "tags": [
                    "portal"
                ],
                "summary": "Просмотр вакансии по ссылке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Короткая ссылка вакансии",
                        "name": "short_link",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Vacancy"
                        }
                    },
                    "404": {
                        "description": "Вакансия не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vacancies/{id}": {
            "get": {
                "description": "Возвращает полную информацию о выбранной вакансии по ID",
                "tags": [
                    "vacancies"
                ],
                "summary": "Получить информацию о вакансии",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID вакансии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Vacancy"
                        }
                    },
                    "404": {
                        "description": "Вакансия не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vacancies/{id}/applications": {
            "get": {
                "description": "Получает все заявки кандидатов для конкретной вакансии",
                "tags": [
                    "vacancies"
                ],
                "summary": "Список откликов на вакансию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID вакансии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Application"
                            }
                        }
                    }
                }
            }
        },
        "/vacancies/{id}/archive": {
            "patch": {
                "description": "Переводит вакансию в статус \"архивная\" по ID",
                "tags": [
                    "vacancies"
                ],
                "summary": "Архивация вакансии",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID вакансии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vacancy archived",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Вакансия не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/vacancies/{id}/dearchive": {
            "patch": {
                "description": "Восстанавливает вакансию из архива (делает активной)",
                "tags": [
                    "vacancies"
                ],
                "summary": "Разархивация вакансии",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID вакансии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vacancy de-archived",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Вакансия не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Application": {
            "type": "object",
            "properties": {
                "ai_score": {
                    "type": "integer"
                },
                "applied_at": {
                    "type": "string"
                },
                "candidate_id": {
                    "type": "string"
                },
                "candidate_name": {
                    "description": "Для отображения в списке рекрутера",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "vacancy_id": {
                    "type": "string"
                }
            }
        },
        "models.MessageTemplate": {
            "type": "object",
            "properties": {
                "body_text": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recruiter_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.Vacancy": {
            "type": "object",
            "properties": {
                "ai_filters": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_archived": {
                    "type": "boolean"
                },
                "recruiter_id": {
                    "type": "string"
                },
                "short_link": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.VacancyCreateRequest": {
            "type": "object",
            "properties": {
                "ai_filters": {
                    "type": "string"
                },
                "is_archived": {
                    "type": "boolean"
                },
                "recruiter_id": {
                    "type": "string"
                },
                "short_link": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "ai-recruiting.onrender.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AI Recruiting API",
	Description:      "API сервис для автоматизации рекрутинга.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
